version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - "8080:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - backend1
      - backend2

  backend1:
    image: nginx:alpine
    volumes:
      - ./backend1/index.html:/usr/share/nginx/html/index.html
      - ./backend1/default.conf:/etc/nginx/conf.d/default.conf

  backend2:
    image: nginx:alpine
    volumes:
      - ./backend2/index.html:/usr/share/nginx/html/index.html
      - ./backend2/default.conf:/etc/nginx/conf.d/default.conf
